services:
  postgres:
    image: postgres:14-alpine
    container_name: simpleauth_db
    environment:
      - 'POSTGRES_DB=simpleauth'
      - 'POSTGRES_USER=simpleauth-user'
      - 'POSTGRES_PASSWORD=12345678'
    ports:
      - '45432:5432'